---
title: "2666"
date: "2024-03-17"
author: "Juan Tellez"
categories:
  - books
  - fiction
  - mexico
---

You can't overstate how long this book is. It's not just that it's 1200 pages, it's that there are no chapters save for five sections/books and that there are huge multi-page paragraphs. There were nights where I would turn the page, see two or three pages back to back of unbroken text and said forget it. I'll pick it up tomorrow.

When you read books this long they invariably stick with you and feel special, like *Infinite Jest* or *Gravity's Rainbow* or *Moby Dick*. There is a rhythm, a kind of trance you fall into reading. You end up reading them in many settings: in bed, while eating lunch, in Florida, waiting in my car, during Christmas, and so on. This one feels like it will stick with me.

The first three sections are good but the last two sections are very, very good. The part about the murders is so eerie and dark and slowly builds momentum; I read somewhere that in total 110 murders are recounted. Klaus is terrifying. And then the last section --- to follow all that --- draws a parallel between the horrors of the holocaust and the murder of women in Santa Teresa but doesn't feel heavy. The end itself is very sweet, a mother who loves her son, sees but doesn't understand how much evil people are capable of.

Bolaño can write like no one else, with an ease and energy that is kinda shocking. The part about the murders alone is shocking, but to shift gears and write about Germany in the 30s and Italy in the postwar period and so on without breaking a sweat.

Not sure where I rank this relative to *The Savage Detectives*, maybe it's ahead.
