---
title: "Anti-Semite and Jew"
date: "2024-06-05"
author: "Juan Tellez"
categories:
  - books
  - philosophy
  - france
---

In *Anti-Semite and Jew*, Sartre reflects on the "logic" of antisemitism in France, at the end of the Second World War and as many French Jews who were deported by the Nazis are beginning to make their return. In a broad sense, he wants to explore how antisemitism works at the level of the individual: what does it "do" for the antisemite to be antisemitic? Why is he this way? In line with his prior work, he sees a sort of psychological dialectic at play in the persistence of these beliefs: antisemites and Jewish people are locked in a mutually "reinforcing" dance.

It's an interesting time to read this book. Since Musk took over, my Twitter feed is full of far-right accounts, many discreetly or openly flirting with antisemitism, Nazi apologism, etc. I'm still in shock about how blatant it is, yet where antisemitism as a concept is most at play in the discourse is as justification to discipline (in some cases deport) protestors of Israel's brutal war in Gaza. It is a crazy time.

This book would be hard to write today. Early on, I felt sympathetic to what he was doing: yes, he's not Jewish, but that does not mean he can't say something interesting about antisemitism. In fact, he is refreshingly candid about how much antisemitism exists in his social circle and much of his theorizing is specific to his experiences in France. On that front, the etiquette today -- that only members of a group should comment on that group -- seems bad!

Then I got to the chapter on the Jews and, well, it's a tough read. He speaks in extremely broad strokes about a group he clearly has little connection to. He describes them as lacking history or culture (because of their perpetual persecution and displacement), and seems to take antisemitic stereotypes at face value. There is a painful portion, for instance, where he explains that the alleged Jewish love of money is related to their need for impersonal exchange (whenever their personal identity is at play, they are at risk). It's pretty awkward.

The first chapter on the antisemite is really all that's worth reading here. And it is a really interesting set of observations, almost aphoristic. He characterizes antisemitism as a *choice* (famously: "if the Jew did not exist, the antisemite would invent him"), that seeks out facts that support the view rather than the other way around, which perhaps distinguishes antisemitism from other forms of "ethnic" hatred. At its core, Sartre diagnoses the antisemite with a desire for impenetrability, a discomfort with the ambiguities of truth.

Especially interesting -- thinking back to Twitter, and the right-wing accounts who are "haha kidding but not really" playing with antisemitic tropes -- is Sartre's noticing that the antisemite fundamentally "plays," that there is a layer of amusement (today he would say trolling) to their discourse. "They delight in acting in bad faith"; they do not stand by their arguments because their beliefs are not rooted in reason but a kind of anti-reason. The tension that Sartre notices between the antisemite (and more broadly the fascist's) love of order and yet the desire to break that order is very interesting: the tendency towards hooliganism, pogrom, destruction. I think it clarifies some things about the concept of the "Deep State" among the modern far right: "Thus for the anti-Semite there is a *real* France with a government but diffused and without special organs, and an abstract France, official, Jew-ridden, against which it is proper to rebel."

Michael Walzer's preface is worth reading too; he does not seem like a fan.
