---
title: "Before the Storm"
date: "2025-11-26"
author: "Juan Tellez"
categories:
  - books
  - history
  - usa
---

*Before the Storm* ends with Goldwater losing in a landslide to LBJ, and GOP leadership, pundits, and analysts proclaiming that a continued shift towards conservatism would doom the GOP to minority status forever. The lesson was that "extremism in the defense of liberty..." could not work at the ballot box. Of course, it would turn out that the shift toward conservatism would happen anyway, and that it would pay dividends with Reagan.

This book was written long before Trump became president, which makes the parallels that emerge between Trump and Goldwater all the more interesting. Both effectively took their party's nomination by force, against the wishes of the establishment, by tapping into some political vibe that -- at least at that point -- was unrecognized. For Trump that current was immigration and resentment of identity politics; for Goldwater, the free market and the Cold War.

Where the two diverge, of course, is that Goldwater was brutally defeated by LBJ while Trump did what seemed like the impossible, twice. There's an interesting difference there: the public seemed genuinely put off by Goldwater's extremism, his desire to dismantle the New Deal welfare state, his international belligerence at a time when people feared nuclear war. Not so for Trump, and perhaps because part of what he does *is* frequently moderate: on abortion, for instance, he is not going to lock himself into an unpopular position.

It's interesting that a book like this might not be considered as "serious" history as something written by an academic historian. A great deal of what Perlstein is doing in this book is laying down a record of what happened, with incredible detail, sourcing, and quotes: that's why the book is 900 pages and who knows how many words -- it's so dense. An academic book, on the other hand, would probably be shorter and less about documenting history than laying out some argument. Personally, I am more impressed by this type of writing.

In all, a worthwhile read, although nowhere near as gripping as *Nixonland*. Goldwater is an interesting figure, but not *that* interesting. And definitely not as interesting as Nixon. The long middle part of the book kind of drags on and only comes alive again when we start seeing more of LBJ's insane-Texan thing. All this makes the length of the book tough to stomach.
