---
title: "The Blood of Guatemala"
date: "2024-06-05"
author: "Juan Tellez"
categories:
  - books
  - history
  - guatemala
---

I was on a reading tear until I got to this book and it totally derailed me. I had to start it a few times and it felt like a slog, even if parts were rewarding. The book is very "dissertation-y" and it is also very specific: basically about the development of national identity in Quetzaltenango, an important city in Guatemala, but one city, primarily in the 1800s.

Still, the book was interesting. The core of it is about relations between the large indigenous population in this part of the country and, first, the Spanish Crown and, later, the (white) Ladino national government. The hook here is that the indigenous community is not without its internal divisions; crucially, there is a stratum of indigenous society that is able to benefit from the colonial arrangement. Some of these are pretty powerful and wealthy; there are these great anecdotes at different points in time of white, Ladino community leaders reaching out for help, loans, etc., from the indigenous community and getting nothing.

Grandin highlights how this elite indigenous class works to protect its privilege at different times throughout Guatemalan history, often in surprising ways. The most interesting way that this happens is in the classic Latin American struggle between Conservative and Liberal parties in the 1800s. Surprising from our vantage point, the Liberals are primarily the villains from the indigenous perspective. In wanting to reform society and erase the boundaries between indigenous and non-indigenous (e.g., assimilating the indigenous population), they come into conflict with the community and especially the elites within the community. During a war in which the Western Highlands briefly declares independence, the indigenous community actually sides with the Conservatives to destroy the short-lived Liberal regime.

Other interesting moments are during a cholera outbreak and then in the 1940s during Arbenz's rule and the short-lived revolution. Indigenous elites actually joined anticommunist efforts to undermine land reform and expropriation efforts by indigenous peasants.

There's some great content here for sketching out how, even under governance schemes that hurt a group overall, there are still likely to be "winners and losers" within the group who will respond to strategic incentives. It's also interesting to see such a powerful indigenous community in 1800s Latin America.
