---
title: "Braiding Sweetgrass"
date: "2024-06-05"
author: "Juan Tellez"
categories:
  - books
  - memoir
---

*Braiding Sweetgrass* is equal parts memoir and "pop science" (I don't mean this pejoratively) exploration of indigenous cultural practices, especially with regard to conservation, the environment, and where those practices overlap and diverge from modern ecology. In broad strokes, Kimmerer makes the case that indigenous practices got ecology right, and earlier, than modern Western science, and that we might live better if we learned from these cultures.

Kimmerer is persuasive, especially in the memoir parts of the book. Her connection to the land and her use of the land to produce things for her family reads as a mindful, grounded way to be in the world that is appealing. I definitely felt motivated to grow something after reading.

In other ways, though, the ideas advanced in this book can feel like well-worn tropes about Native American culture that I have never found super convincing. For one, *which* culture are we talking about? She speaks in general terms, but her own indigenous background is a specific one (Potawatomi). Do "all" indigenous cultures share this perspective on nature? Or only some? How do they vary? These would be very interesting questions, maybe not fair to pose of her book since that's not its goal.

One thing I do find dissatisfying is that she takes indigenous cultural *beliefs* and *principles* as what make these cultures so effective at ecology. To think of nature as providing us gifts (she describes a strawberry plant as "staying up all night" to make the strawberries she consumes the next day) is beautiful, and you can imagine how, if you truly embraced that worldview, you would treat nature more gingerly as a form of gratitude. The problem is you can do something analogous to what she is doing with indigenous practices with the major world religions, or other belief systems. To "turn the other cheek when struck," or to "love thy neighbor as thyself" -- these also sound great and beautiful. Of course, the problem is no one actually lives out these principles, not even their adherents. So: sure, indigenous cultures have these belief systems that are praiseworthy. But do they actually live them? There, I am less sure.

For instance, the Potawatomi (and many other indigenous tribes) practiced slavery and raiding. Raiding is where you notice that a village nearby has grown a bunch of stuff that is poorly guarded. So you suit up and, through violence, take (almost) everything, leaving the survivors half-starved. How do people of all belief systems seem to hold these beautiful ideas and yet nonetheless behave in ways that would seem to contradict them? I would find this a more interesting approach to writing about indigenous culture than this trope of indigenous people "living better" than us in the West.

In the end, my gripes here all come down to a framework where indigenous cultures and practices are painted in the best possible light and contrasted with the worst elements of Western culture. I get why she's doing this, obviously, given how these cultures have been devalued historically. But a more nuanced description of indigenous cultures would be more interesting and useful. Part of the power of the indigenous cultural practices she describes is in the strength of the norms within these communities; without these norms, the gift economies she describes, for instance, could not be sustained. But norms carry a price too because they must be enforced. Does the enforcement of these norms mean that a high level of conformity is necessary within these societies? And does that conformity clash with the value we place on individual liberties?
