---
title: "The Fort Bragg Cartel"
date: "2025-10-07"
author: "Juan Tellez"
categories:
  - books
  - usa
  - war
---

This book, about a series of drug-related murders in Fort Bragg (Fayetteville, NC), can be read at a couple of different levels. The lowest level is "true crime," where the book is simply reporting on these strange, scandalous murders in what seems, from a distance, like an elite, prestigious subset of the military. At this level, you wonder why not watch the Netflix/HBO docuseries that I'm sure is already in the works.

One level up is a story about two more "universal" dynamics in how countries prosecute wars. The first is about covert action, which the average person imagines is an important yet relatively small proportion of how wars are fought. Harp argues that covert actions are in fact a large proportion of fighting abroad, and that they look much closer to "domestic," mafia-like forms of violence -- assassinations, poisonings, blown-up cars, etc. -- than the image the public has of uniformed army personnel carrying out discrete missions abroad. An interesting claim in this book, which I had not considered before, is that the growth of special operations units like Delta Force takes off post-Vietnam and post-US public reckoning with the CIA's actions abroad, which resulted in House/Senate intelligence committees to whom the CIA and FBI are supposedly meant to report their behavior. Delta Force-like units get to do what the CIA was doing during the Cold War without that oversight.

The second dynamic is about recruitment: that who armed organizations (armies and rebel groups alike) recruit matters for how civilians are treated in war. Abduct your soldiers, rely on conscription, or provide "moral waivers" (as the US did during the surge) and you get lower-quality recruits who are in turn more likely to do bad things and contribute to a culture where evil is met with impunity. At an interpersonal level, there is something almost tragic for the operators themselves who, in receiving constant slaps on the wrist for egregious behavior, never face consequences or other "checks" on their behavior that might help them correct course.

In the special forces case, Harp is emphatic that the US is effectively selecting for near-criminal types, who not only seek out and commit gruesome acts of violence but also blatantly engage in drug trafficking. The drug trafficking part of the book is easily the most shocking: special forces troops spending years in places like Afghanistan, where there is both a lively drug trade in opium *and* a total corruption of the political system by the drug trade, creates opportunities for these operators to become involved in drug trafficking. This is also a story as old as time: states make allies in foreign wars with groups who are often "unseemly." This is a feature and not a bug, since the groups most likely to ally the foreign power in domestic conflict are those who are most rapacious to begin with.

One more level up is the level of "parapolitics," a genre of writing about politics that leans on the conspiratorial, arguing that what we see on the surface is a reality that has been massaged by shadowy forces directing everything behind the scenes. Harp is clearly inspired by works in this genre and aims for some of his claims to land at this level. This kind of work, of course, makes me nervous because the scale of the claims being made are enormous; it is difficult to see how strong of evidence we would require to accept them. Harp here, for instance, casually says that the war in Afghanistan was a kind of elaborate ruse to funnel taxpayer money to defense contractors who in turn kicked shares back to politicians in DC to "keep the war going." This is said about every war, and it never really makes sense.

One reaction to Harp's claims here is to ask how new this is in world history. My guess is: not very, neither in the West nor anywhere else, especially in the past. States carry out nasty, covert operations in their enemies' territory; they hire brutal people who do brutal things; the gush of money used to fund this stuff is subject to substantial corruption. Why then is this so shocking to hear? This is especially "funny" when you consider Harp's politics, clearly in the "anti-imperial" / The Intercept / Radio War Nerd camp of (putting it uncharitably) seeing everything through the lens of "anything the US does is motivated by imperial ambitions / internal corruption and everything its enemies do is a form of maybe noble / at minimum understandable resistance." These people will be the first to tell you that international norms are a lie, international law is a smokescreen, etc., but then point, exasperatedly, at violations of these norms and laws.

My guess is that what Harp is rubbing against is this sense that we live in a fundamentally new era, where militaries are perfectly under civilian control, and where the penalties for human rights violations are so severe that even if soldiers want to commit war crimes they rarely do so because they fear the repercussions. What this book shows is that this is closer to fantasy than reality.
