---
title: "The Frontier Effect"
date: "2024-06-05"
author: "Juan Tellez"
categories:
  - books
  - colombia
  - war
---

*The Frontier Effect* is a book about Uraba, in Colombia, a region near the border with Panama. Uraba is a microcosm of the country's violent conflicts -- you can truly see every element of the conflict at play there. Early on, an "underdeveloped" backwater that grows quickly due to the booming banana industry and early colonos. Later, a hotspot for guerrilla organizing, especially the FARC and the much less heard of (though fascinating) EPL. And much later, the place where the paramilitaries would exert seemingly unparalleled control over economic and political life.

Ballve is interested in the role of the state in Colombia's wars, and especially in Uraba. It is a common refrain that in places like Uraba, the state is weak or absent, and so Hobbesian violence emerges. Ballve argues that, instead, in these places other kinds of order emerge: imposed first by the guerrillas (who bring significant political infrastructure to the region) and later the paramilitaries.

Ballve's narrative of the paramilitaries is where the book really shines. In many readings of the conflict, the paramilitaries are shadowy figures with little or no ideological worldview, notoriously violent and predatory. Ballve's depiction is, frankly, surprisingly sympathetic (or at least more nuanced). He establishes quickly and convincingly that the paramilitaries, like the guerrillas, relied on social bases of support. And like the guerrillas, they had a vision for the region -- a vision that is confused, unclear, and incoherent in parts, not so dissimilar from the guerrillas.

I knew about parapolitica, and I've written about the dispossession of peasant lands and the ties to the palm oil industry. But the level of institution-building the paras took on surprised me. The extent to which they resettled these lands with new peasants, who expressed some degree of loyalty, also surprised me. There are also a ton of eye-popping anecdotes in here I hadn't heard about: the paras' foray into ecotourism, their development of JACs in the region, and the fact that when land restitution ultimately comes to Uraba it is with tacit para approval.

Before reading this book, I thought the absence of the effective, legitimate state in large swaths of Colombia's territory was a major factor in the war. After reading this, I still mostly feel the same way. I'm not sure I buy the move Ballve makes here -- that state absence can't explain violence, because other orders emerge. The orders he describes don't seem to last all that long, and they seem normatively worse than an effective, legitimate state.

All said, impressive book!
