---
title: "The Future Is History"
date: "2025-11-18"
author: "Juan Tellez"
categories:
  - books
  - russia
  - democracy
---

There's a spectrum of writing about Putin's Russia and, indeed, all major non-democratic countries aligned against the US (Iran, Venezuela, etc.). At one extreme are the "anti-imperialists" who see no discernible difference between the quality of democracy in the US and that of Putin's Russia. If CNN will not call the war in Gaza a genocide, then there is no difference between that and Russia's state-run TV station. These same people will describe everything Russia does abroad as "strategic," a necessary reaction against the aggression of the West, adjectives that never seem to apply when Western countries do these exact same things. At the other extreme are painfully earnest liberals like Masha Gessen who will not concede even an air of similarity between the US and Russia, the latter literally "totalitarian" and pathological. As one can guess, I find both of these extremes bizarre.

I really did not like the tone of this book, which insists on not just describing events on the ground but telling the reader how they should feel about them. This gets tedious, fast: when the police beat up peaceful protestors, I don't need to be told this is a "brutal violation of human rights" -- I get it. I agree! By the same token, we are given precious little in the way of description of Alexander Dugin's worldview, which Gessen clearly sees as post-hoc bullshit (Gessen even tells us Dugin was a layabout who refused to work and had life handed to him). Again, I don't need convincing that Dugin is "bad" but as a non Russian-speaker I would love to know what he's actually talking about. It reminded me in this way of Timothy Snyder's *Bloodlands*, another earnest liberal take on Russian politics. With Gessen's book, however, it is more justifiable because what she is actually doing here is something more formally interesting, blending parts of her life story into a kind of political memoir. The memoir portions of the book and the descriptions of life under Putin are where the book shines, even as it primarily relays the lives of relatively well-to-do media types.

Why has Putin ruled Russia for so long? For an earnest liberal like Gessen, the answer is highly pessimistic: the Russian people, essentially, developed a kind of Stockholm syndrome during the Soviet Union and they want nothing more than to go back, be enveloped in the authoritarian leader. This is a highly cultural, psychological explanation that is just not convincing. But one gets the sense Gessen is also speaking out of anger here, which is understandable.

Book could have been 70% as long.
