---
title: "The Golden Road"
date: "2024-06-05"
author: "Juan Tellez"
categories:
  - books
  - india
  - history
---

Ancient history is a tough read for me. To go from a modern world with roughly 200 state units, all organized in relatively recognizable ways, to the ancient world where the relevant state actors might be proper-noun kings, emperors, etc. -- I can't find my bearing and my eyes begin to glaze over.

I was hoping Dalrymple would break open the ancient world for me. I'm a huge fan of his work. *Return of a King* was excellent, and his *Empire* podcast is great. Sadly, it didn't take. I read the first few chapters carefully; the one on the early history of Buddhism was interesting. We associate Buddhism so much with the Far East, and Hinduism with India, that we forget Buddhism was originally Indian. I was also reminded of *The Last Temptation of Saint Anthony* in the way that at the time when Buddhism is beginning to form as a spiritual practice there are dozens and dozens of other existing religious belief systems in India. It would take state power in the form of Emperor Ashoka to spread Buddhism throughout the subcontinent, and for similar moves to take place in China, powered by traders and travelers.

But the rest of the book was a slog and I largely skimmed it.
