---
title: "Hard-Boiled Wonderland and the End of the World"
date: "2024-06-05"
author: "Juan Tellez"
categories:
  - books
  - fiction
  - japan
  - sci-fi
---

Really struggled with what score to give this. Of any author, we might have the most books at home of Murakami's. I loved *Norwegian Wood* and *Wind-Up Bird* when I read them in college, but then mostly lost interest. I did read the Tokyo subway attack book while traveling in Japan two summers ago. My wife really loves his books and has read more of them.

There are some amazing moments in the book; the last third is particularly strong. Murakami is great at writing people doing mundane things: drinking beer, eating noodles. It feels really comforting. And there is this long sequence where the narrator is escaping through Tokyo's sewer system that is visceral and creepy. But I mostly didn't care for the "end of the world" portions of the book, probably because it veers into this cloying, twee sort of "all you need is love" thing that some sci-fi tends to use as a way to resolve the tension of the overly complicated puzzle they've laid out (thinking here of the awful movie, *Interstellar*).

As an aside: I'm blown away by how similar this book is to the TV show *Severance*. The narrator is essentially severed; he's been trained (and surgically altered) to be able to complete tasks independently, to where one side doesn't know what the other is doing. And his alter ego, in "end of the world," is him but doesn't remember himself. He's tasked with completing these strange tasks in this strange world that no one explains to him but that he ultimately decides is oppressive. I'd be shocked if no one on *Severance* read this book.
