---
title: "A History of Modern Uganda"
date: "2025-10-15"
author: "Juan Tellez"
categories:
  - books
  - history
  - uganda
---

With a title like this, you imagine an introductory, chronological history of Uganda, one that is maybe focused on the 20th century. This is instead a series of essays on the history of Uganda (in strange order), and definitely not introductory; the level of detail is truly bizarre at times. If you read this without some basic Ugandan history in your pocket you will get lost. Even then, you will probably skim large portions of the mega-paragraphs in this book. As always, however, there are interesting things here.

First are the parallels between Obote, Idi Amin, and Museveni, each of whom take office (by force!) on a mission of unifying the country, rejecting "sectarianism," and whatever was in vogue at the time with respect to economic policy (with Amin it was state-led development, with Museveni, structural adjustment). These good feelings don't last, at least in part because, in taking power by force, the country is left full of real and potential enemies that need to be contained or repressed. I ended up drawing on this a lot for my paper on Abiy Ahmed in Ethiopia.

Second is the deeper history you get here of precolonial Uganda, a period I had only read passing reference to. The little I knew, echoed here, is that prior to the British Ugandan Protectorate there were a series of kingdoms that were fairly autonomous. The British team up with seemingly the most powerful of these, Buganda, to conquer and incorporate the others, although only partially; in the end, the North of Uganda is left famously underdeveloped and there are other kingdoms that retain more autonomy. These kingdoms persist politically until Obote famously breaks their back, brought back later by Museveni but only as cultural institutions. An interesting accident of history here is that the North, by virtue of being rebellious and "needing" to be forcefully conquered through military rule, comes to both develop a kind of militaristic culture and becomes associated with militarism in the eyes of the British. The British then heavily recruit from the North to staff the Ugandan military, which ultimately lays the foundation for the conflicts and coups post-independence.

This precolonial history gets at the question of what role colonialism had in Uganda's trajectory (and the development or underdevelopment of Africa more broadly). It seems to me both progressives and conservatives largely assume that, pre-Europe, there was "not much there" politically speaking; it's the Europeans who either ruined (progressive) or improved (conservative) the continent. At least in Uganda, however, there are clearly large political units in existence, engaging in conflict and conquest with one another. Reid, in fact, describes the British as effectively being co-opted by Buganda against its rival kingdoms. The puzzle then is: on the one hand, it seems clear that the British lumping all of these kingdoms together and putting them under the thumb of one group would lead to bad outcomes. On the other, it is not clear that these kingdoms absent intervention were on the road to prosperity (none of them, for instance, were strong enough to rebuff the British), or that they would have avoided conflict with one another (they were fighting long before the British arrived).
