---
title: "How to Talk So Little Kids Will Listen"
date: "2024-06-05"
author: "Juan Tellez"
categories:
  - books
  - parenting
---

*How to Talk So Little Kids Will Listen* is a sequel (?) to the classic 1970s parenting advice book. From what I can tell, the core ideas are much the same.

An interesting thing about the book is that it doesn't foreground a particular philosophy about child-rearing. There is definitely one there, but it is more subtext than text. The authors are not telling you "this is the way the world works"; they are more presenting approaches to problem-solving common challenges with children.

The philosophy that the book does espouse about child-rearing is that one should take kids, and especially their emotions, seriously. This might sound obvious, but as a parent, it often is not. Imagine a toddler asks you to cut a strawberry in half, regrets it and asks you to reverse that process, then tantrums when you cannot. In these moments, it is hard to see past the insanity of what they are crying about. In other words, it is easy to see little kids as irrational, or at least the stuff that upsets them.

And maybe it is. Maybe they get upset about a wider, less compelling set of things than adults do (though if we are honest, we let ourselves get upset about plenty). But they are upset nonetheless, and you cannot tell someone who is upset not to be upset. It doesn't matter if the reason they are upset is that they were unceremoniously fired from work, or if they ate their M&Ms in the wrong order.

This was a really effective component of the book: drawing analogies between what children are feeling in these moments and what we feel as adults. These analogies make very clear why acknowledging emotions is important.

In practice, this means literally talking to your child with empathy about what they are upset about. It also means modeling how to deal with these emotions and problem-solve, which is not easy. But it rings true to me.

I also appreciated how much the book highlights the parents' experience; it's not just about the kid. There's a short chapter in particular on when parents feel overwhelmed by anger at something their child is doing, which I found refreshingly candid. That anger is not ideal, but it is also part of life: children will run into people who they will make angry or who will become angry at them for a variety of reasons, people close to them or strangers. They need to learn how to deal with these moments, and it is also instructive post-rage to come back together and "make up": that this is a healthy part of human life.

I've been going through some parenting struggles and this book really did it for me, I'm all in with this shit.
