---
title: "The Hundred Years' War on Palestine"
date: "2024-06-05"
author: "Juan Tellez"
categories:
  - books
  - history
  - israel-palestine
  - war
---

The title made me think this would be a doorstopper history of the hundred years of conflict in Palestine. But the book is actually pretty short (around 250 pages) and less of a history than an argument. Khalidi, who was involved in much of the politics of the time via Lebanon, takes the reader through the conflict in chronological order but focuses on the critical points of debate, e.g., was there really a pre-1948 Palestinian "people," did Zionists intend to expel the Arab population or was it a "natural" by-product of war, how sincere were efforts at Oslo, etc. You can guess the direction of these arguments, which is not to say that they are not well-made or unconvincing. But I was hoping for a bit more; especially disappointing (no fault of the author's) is not having Khalidi's views on October 7th. That said, he is a passionate advocate of his people and someone with credible experience and analysis.

Khalidi's main thesis is to argue that Israel's treatment of the Palestinians is a form of colonialism, down to the very first Zionist movements which, Khalidi argues, imagined their project as a colonialist one, one that they only move away from once colonialism takes on a bad taste post-WW2. That said, even if we accept this premise, there are some unusual features here, the most obvious one being that unlike other settler colonial states, Israel has a kind of cultural and normative claim on the land that enjoys a decent level of global acceptance, given the fact that Jewish people have lived in the area (as minorities) for thousands of years, their historical persecution in other countries, and of course the experience of the Holocaust. As Khalidi notes, this bit of "bad luck" for the Palestinians amounts to it seeming implausible to say that Jewish people were "colonizing" the land where their religion began.

Khalidi is also much more temperate in his claims and his apportioning of blame than many others writing on this topic. I read Max Blumenthal's *Goliath* while I was traveling through Israel in the 2010s, the tone of which is so hysterical it is nearly unreadable. Khalidi is plain in seeing the early objectives of the Palestinian movement -- a full return to the pre-1948 status quo, the rejection of Israel as a state -- as ultimately foolish. It would be interesting to hear his thoughts on "river to sea" discourse post-2023. Khalidi also seems to have especially little good to say about the PLO and Arafat, whom he sees as ineffective and out of touch, the latter a function of the organization's exile to Tunis.

This was an interesting dimension I had never properly appreciated. The PLO became *the* actor representing the Palestinian people during much of this time and yet its leaders were not even living in the territories (obviously, because they could not). Khalidi seems to think they absolutely botched Oslo I and II and agreed to things they should not have agreed to out of a position of weakness. Another interesting blunder is Arafat's decision to waffle on and then endorse Saddam Hussein's invasion of Kuwait, an invasion that literally every other Arab state had denounced or explicitly resisted via arms because of its obvious violation of state sovereignty. This led the PLO to lose Gulf funding and experience other setbacks that hurt during the Oslo accords. Khalidi also has only criticisms for Hamas and Islamic Jihad, whom he sees as setting the Palestinian cause back during the second Intifada, especially through their use of suicide bombings.

Who is right and who is wrong in the debates that Khalidi is engaged in is obviously important. But right or wrong on these questions does not imply answers as to what should be done now that we are 100 years, as Khalidi says, into this conflict. Even if one perfectly argued from first principles that the Sioux should not have been expelled from the Dakotas, it does not follow that we should displace some white family of five in Bismarck. I think Khalidi would agree. He is unambiguous about this: there is no solution to this conflict in which Israel does not continue to be a state. Towards the end of the book, Khalidi sets up three endpoints for colonial projects: full defeat or extermination of the indigenous population (i.e., North America); a reversion to indigenous rule via revolution (i.e., Algeria); a reconciliation of the dominant and subjected populations (i.e., South Africa). You can tell his hopes are in the last outcome.

Again, would love to know his thoughts on the situation post-October 7th.
