---
title: "I Am Dynamite! A Life of Nietzsche"
date: "2025-09-09"
author: "Juan Tellez"
categories:
  - books
  - biography
  - philosophy
---

"One repays a teacher badly if one always remains nothing but a pupil."

Biographies have a bad habit of lionizing their subject. There's even a word for this, "hagiography," and it's lame because you feel like you're being spoon-fed something instead of coming to your own conclusion. To my surprise, *I Am Dynamite!* does the exact opposite of this, although it's not clear to me how intentional. This is, on the whole, a pretty unflattering portrait of Nietzsche, and not because of his supposed association with Nazism, which the author is adamant about rejecting.

The book is unflattering on a personal level: Nietzsche seems like a small man, neurotic, delusional, totally flaccid. There is at least one woman in the book who, upon first meeting him, is shocked by the discrepancy between Nietzsche the writer (passionate, virile, confident) and Nietzsche the person, who seems to melt into the background. I felt the same sense of surprise whenever the author quotes directly from Nietzsche. Anyone who's read him would probably agree he does not lack passion, whatever you think of his ideas.

Three things stick with me by the end of the biography. First, the unusual, libertine culture among cultural figures during this time in Germany. At the center is Richard Wagner, whom Nietzsche is obsessed with, almost to the point of an erotic relationship. There are many love triangles, and at one point Nietzsche even enters a sort of polycule with a woman and a man, the latter two having paired up first on the mutual agreement of no sex, since they both found it disgusting. It is incredible how much of Nietzsche's short life is spent on these relationships.

Second, the degree to which Nietzsche's illnesses shaped his life. I knew Nietzsche had been ill and that he had died in a state of steep mental decline, but I had imagined it was more self-contained. In fact, it was the bulk of his life. He would be ill for long spells, sometimes half the year or more, and his vision rapidly deteriorated in adulthood. This radically shrank his ability to work, and is one reason for his interest in aphorisms; he did not have enough time in good health for longer-form writing.

To be sick during this time seems especially gruesome, given the low quality of medicine. He spent years receiving painful treatments (enemas, bleeding) that (we now know) have no bearing on what ailed him. There are also some darkly funny moments here: at the time, problems with eyesight were thought to be caused by excessive masturbation. Since Nietzsche was single late into adulthood and either seemingly averse (or just very private) about sex, people speculated that he was a masturbator. Incredibly, Richard Wagner writes letters to Nietzsche's doctor expressing his belief that Nietzsche's ailments are the result of excessive masturbation and (IIRC) the doctor even recommends Nietzsche visit brothels.

Third, the incredible story of Nietzsche's sister, who seems like a real piece of work. I vaguely knew, before reading this book, that Nietzsche's association with Nazism was somehow her fault. It turns out his sister was a rabid antisemite, something that, interestingly, neither Nietzsche nor their mother shared despite all being very close. They seem almost bewildered by her obsession with the Jews. In one incredible moment, the sister marries an even bigger antisemite than her and they move to Paraguay to start a colony, "Nueva Germania," that would exist on antisemitic ideals.

The colony fails and she fails, in almost every regard, except that she is the one left holding all the cards when Nietzsche's mother dies, leaving her unopposed to manage his archive and to live with him while he is in this horrible catatonic state. Truly creepy. I would read a book just about her.
