---
title: "A Popular History of Idi Amin's Uganda"
date: "2024-06-05"
author: "Juan Tellez"
categories:
  - books
  - history
  - uganda
---

I remember watching *The Last King of Scotland* in high school and thinking it was great, even rewatching it a few times. It probably says something that, despite watching the movie so many times, I had no idea what country Idi Amin was in charge of, or where Uganda was on the map. I picked up this book to correct my ignorance as I start working on a research project with some relevance to Uganda.

This is a straightforward academic text. Every chapter could be a standalone article; each starts with an overview of the big picture takeaway, then a page break, the empirical content to support the takeaway, and then a page break to the conclusion. I will never understand why academic writing, supposedly aimed at an audience more attuned to difficult reading, traditionally spoon-feeds the reader like this. That said, an interesting and worthwhile book about Uganda's most famous leader. Less a comprehensive overview and more a series of chapters that each touch on a theme of his rule.

Here are some things that stood out. First, the fact that Uganda is composed of kingdoms, which persisted through British colonialism and into independence. Each kingdom was pretty close to autonomous, with its own laws, parliament, and even police force. For Idi Amin's story, the most important kingdom is Buganda, encompassing the modern-day capital of Kampala. During independence, each kingdom seems to want to go its own way, especially Buganda. There are also strong inter-ethnic tensions among the country's many communities.

A weak electoral process brings Obote to power who, because of the pre-existing kingdoms, has little in the way of actual power. His first move is to crush the ancient kingdoms, famously the kingdom of Buganda. Given these pre-existing forms of political organization and hostile neighbors, Obote's government is a "nervous state," paranoid of overthrow. With good reason, it turns out: he is ultimately overthrown by one of his generals, Idi Amin, while Obote is out of the country in 1971.

Second, that at the time of independence there are a number of South Asian people living in Uganda (analogous to other British colonies, such as Trinidad and Tobago). These communities skew better off, tending to own significant amounts of small capital, businesses, etc. There is deep resentment of this population: one of the earliest forms of popular mobilization around independence is a boycott of South Asian businesses. Idi Amin's early rule will focus on expelling this community from Uganda as part of his so-called "Economic War." This is, by the way, how we get Zohran Mamdani as the likely mayor in NYC; his father is a famous Ugandan academic who was expelled during this time.

Third, while Idi Amin's brutality is well known (the "Hitler of Africa"), I had less exposure to his efforts to make Uganda the frontline of anti-colonial struggle in Africa. A very interesting moment is that early on (even pre-coup, it seems) he is in close contact with Israel, who offer him training and support. But after a trip to Mecca in the 1970s he breaks off all contact with Israel and pivots to a Gaddafi-inflected pan-Africanism. He seems to wage very little actual war on this front, mostly a matter of presentation: the author tells a story of Idi Amin training and arming fighters to go to South Africa and Rhodesia, but this is all for show -- they are made to return weapons and even uniforms after the photo op. Culturally, Idi Amin's regime will do a lot more: banning miniskirts, wigs, Evangelical Christianity, changing the names of streets, etc.

In the end, Idi Amin's regime ends when he invades neighboring Tanzania and the latter counter-mobilizes, invades Uganda, and unseats him, shocking everyone given Idi Amin's grip on the country.

As with reading about any leader who uses repression to close off imagined coups, one wonders to what extent the leader's level of paranoia is warranted. Liberal-democratic retellings of these periods (thinking here of the Southern Cone countries, or the Soviet Union) tend to emphasize the "imagined" part: that the paranoia, fear of an internal threat, of wreckers, etc., is objectively overblown. But if you personally couped your predecessor, what else are you supposed to think?
