---
title: "Just and Unjust Wars"
date: "2024-06-05"
author: "Juan Tellez"
categories:
  - books
  - philosophy
---

I took a moral philosophy class in college that has stuck with me for a variety of reasons, one being that the professor told us all that semester that he had been denied tenure and would be dismissed from the university. At the time, I thought, "wow, that sucks," but as I've gotten older the pure horror of it has set in: to have one of the few tenure-track professorships in philosophy and to lose it is brutal. And to relay this to a bunch of college students is worse.

I loved that class and bring this up because the best parts of this book remind me of it. Part of what's great about philosophy is to encounter some moral question, have a strong intuition about its answer, and then have the philosopher throw examples at you that break your intuition. Just one example from the book: the violation of Belgian neutrality by Germany is clearly bad, but what about British violation of Norwegian neutrality in WW2?

Walzer is fairly "moderate" when it comes to what makes war just or unjust. He gives states and soldiers a fair amount of leeway in waging war -- although it's not always so clear to what extent Walzer is making the case for a moral stance versus simply describing the existing conventions around war. He's good at "steelmanning" what might at first seem like morally noxious stances, for instance, that retaliatory violence could be permissible in war. I was pleasantly surprised by this; he thinks through the issues deeply and with some degree of compassion for the people who fight. There are places where I think he is totally convincing (the use of the nuclear bomb was immoral), and places where he is less convincing (his arguments around the Vietnam War), but he's clear and effective.

My favorite chapters: on the use of indiscriminate violence against civilians (e.g., fire bombing of Germany and Japan); on the use of the nuclear bomb; on how technology changes the war convention (e.g., the introduction of submarines to naval warfare); the chapter on guerrilla war.

PS: picked this up because it is apparently frequently assigned at West Point.
