---
title: "La dimensión desconocida"
date: "2025-01-21"
author: "Juan Tellez"
categories:
  - books
  - chile
  - fiction
---

*La dimensión desconocida* is a blend of fiction and memoir. We follow the author as she traces the lives of a variety of real people who lived through Chile's dirty war. At the center is "the man who tortures," a man -- and a real person, Antonio Valenzuela Morales -- who participated in torture and forced disappearances during the dictatorship, defected, revealed all to the press, and fled to France, from where he would continue to provide testimony, validate faces in photographs, and more.

This book was headed for a 3/5 star rating but it won me over. A lot has been written and filmed about Chile and Argentina's dirty wars; it would seem the well has run dry. What the author does best is vividly capture how the dirty war stained everything about ordinary life with horror. What was unique about the dirty war was how centrally located it was: these are not "human rights abuses" happening overseas, or in Abu Ghraib, or in Guantanamo Bay. It is as if in Times Square or Central Park, in some nondescript building, agents of the state were brutally torturing their captives. The torture centers are not special institutions; they are not the concentration camp. They are (now) regular homes, or offices.

What's more: the torture was happening and everyone knew. Nona notes this again and again -- people are snatched up in broad daylight, pulled out of a bus, and everyone can see but pretends not to. She could be sanctimonious about this but she is not; it is just a fact of life, and she is not telling us she would have done differently. She is also surprisingly empathetic towards "the man who tortured," who we learn was really just a boy when he was compelled to torture. It's an interesting balance: a book that on the one hand is deeply critical and on the other primarily conveys the feeling of empathy.

The weight of the disappeared is also captured movingly: the sheer terror of someone vanishing without a trace. There's a devastating moment early on, when some of the first bodies are found, and the families who are searching first realize that what they are likely looking for at this point is bodies.

There's also an incredible amount of history here that I simply did not know. I had no idea how deep into the end of the Pinochet regime disappearances and violent reprisals kept taking place.

The author is and was deeply involved in activism around historical memory in Chile. I think that's perhaps the reason why the book doesn't grapple with the fact that, for many in Chile, the dirty war was something more distant, either because of when they were born or because those in their social network were left relatively untouched. She makes small allusions to this -- her son being too bored to join her at the marches -- but to me, this is part of what's interesting about debates over historical memory. Someone more removed could look at that time period and think, "well, if the government was known to be in the business of hunting and killing communists and socialists, why would anyone be one during this time? Unless..." I think this kind of thinking permeates moderate opposition to historical memory, and it's not an unreasonable first glance at these situations.

That said, I think (Marco Rubio voice) this book totally dispels with the notion that the dirty war was primarily or mostly targeting subversive elements. The book makes the powerful, simple, maybe obvious point that being a communist does not mean the government gets to torture and kill you. The book does this by showing us again and again how cruel and especially cowardly the dirty war was.
