---
title: "La guerra del fin del mundo"
date: "2024-06-05"
author: "Juan Tellez"
categories:
  - books
  - fiction
  - brazil
---

The "end of the world" in the title refers to a remote town in the state of Bahia, Brazil, where an astounding 25,000 people, led by a messianic figure and cult leader known as Antonio Conselheiro ("Anthony the Counselor"), lived in open defiance of the Brazilian state in the late 1800s. The town, Canudos -- apparently now gone, flooded by a dam built by the country's dictatorship in the 1960s -- became the site of Brazil's bloodiest civil war, which saw federal troops fighting bitterly with residents over control of the town, effectively exterminating its inhabitants in the process. The novel is about the War of Canudos, told from the perspective of various characters on both sides of the conflict.

A messianic figure emerging in Brazil at this time, when the Brazilian republic is just born and slavery is abolished; the unorthodox nature of the Counselor's belief system (anti-republican, monarchical, anti-slavery, anti-metric system); the fact that the residents successfully repel multiple waves of federal troops, killing a famous general in the process -- this background gave me very high expectations for this novel. This is rich history, in a part of the country that receives little attention. The geography is brutal: Brazil's *sertao* is poor, plagued with droughts that produce famines, a kind of desert outback which outsiders rarely associate with Brazil.

Sadly, my high expectations were not met. I was very disappointed in this book. What was I expecting? The War of Canudos is so bizarre, in some respects so particular, that I wanted someone who could extract meaning, give me a sense of what these people who gathered at Canudos wanted. This event is important, forgotten to history, but what does it *mean*? I did not come away with a sense that Vargas Llosa (RIP, one of the GOATs) has a clear, convincing view of what the War of Canudos means.

The Counselor himself is sparsely detailed in the novel; he doesn't speak much, and there are obvious parallels to the biblical Jesus. The reader's view of both the Counselor and his followers feels modern: these are people with strange beliefs, cult-like; there is not a ton of room for empathy for these people as *believers* (although certainly as victims, or as the oppressed). I wanted a sense of what it would *feel like* to believe, but we rarely get much interiority into these characters. Many simply seem to become entranced or bewitched soon after meeting the Counselor. Now, maybe this is the truth about what happened in Canudos, but it's not so compelling.

The other side of the narrative follows the military and those characters who are foreign to the region. Here, too, I think there is a disappointing lack of engagement with really interesting ideas: you have a new republic, but there are debates about what it should look like, and a clear clash between a kind of modernizing liberalism and a reactionary conservatism that is one of the turning points of Latin American politics in the 19th and 20th century. In between is this town that doesn't want to be incorporated. Yet Vargas Llosa makes it fairly clear that on the military side there is not much beyond cynicism and desire for control. Again, maybe the truth, but it didn't grab me.

In the end, the conflict itself feels like more of a backdrop to a story that is primarily a romance, with grand, sweeping emotions and characters who feel very strongly. As I read, the movie I kept coming back to was *Gone with the Wind*. That's fine, but it didn't grab me. And to top it off: this is a very long book, and dense with characters. Honestly, a slog to get through.
