---
title: "Little Labors"
date: "2024-06-05"
author: "Juan Tellez"
categories:
  - books
  - parenting
  - memoir
---

*Little Labors* is a series of essays / observations about being a new parent (mother). I ordered this after hearing it recommended on a podcast. The hardcover looks great: tiny book, attractive orange cover (a color that comes up in the book). I've seen the book pitched as useful / interesting for people who are *thinking* about having a baby, but I found it great as someone who already has a baby. And it really is about *babies*, not kids in general.

There are some great bits in here that resonated with me. Early on she describes expecting her baby (whom she calls "puma" early on and other animal names as the baby ages) to be a kind of "sophisticated form of plant life" that she would only truly connect with once they were older and could communicate. But the connection is immediate, as she says, "intoxicating." The sense of feeling "suddenly older" once the baby arrives also hits home.

The non-memoir parts of the book are kind of like cultural studies for babies: interesting observations about the ways babies and mothers are depicted and the space they take up socially. For instance, she notes how few "mother writers" there are (writers who write explicitly from the perspective of mothers) and (in my opinion, accurately) claims the two most famous contemporary mother writers are probably Louis CK and Knausgaard. What's up with that?

Fun, light, interesting read. A bit "MFA-ish" at times but a nice palette cleanser after *Temporada de huracanes*. Have added some Japanese lit to my expanding wishlist.
