---
title: "Lituma en los Andes"
date: "2024-10-02"
author: "Juan Tellez"
categories:
  - books
  - fiction
  - peru
---

*Lituma en los Andes* is a classic mystery novel that follows a cop stationed in a remote, highland mining town in Peru rumored to be at risk of capture by the Shining Path. I bought this a long time ago at the recommendation of Kathryn, and was eager to read it because of my interest in the Shining Path.

The basic idea behind the novel works great: Vargas Llosa uses the mystery genre to set up this thick atmosphere of paranoia and vulnerability that captures what life in one of these towns might feel like. People are disappearing, there are rumors of insurgents who, any day now, will strike, take the town, and submit some (whom?) to revolutionary justice based on (often false) denunciations, but no one knows when or if it will happen. Seeing all of this from Lituma's perspective, an urbanite Peruvian who is just as foreign as we are to the highlands, is great.

The town itself is beautifully rendered: the fast-shifting climate in the Andes, the sort of terrifying/alive sierras, avalanches, the mining town where there is nothing to do but drink, where there's this mix of new and old highland cultures.

I *was* worried going in that this is a book about a left-wing group written by a famously right-wing Peruvian. Could he square that the group, despite doing awful things, grew very rapidly and garnered a lot of support around varied parts of Peru? As with some monster movies, once you actually see the "monster" (here, the Shining Path) the book loses some of its power. The view you get of the Shining Path, at times, is of a cartoonishly evil group.

But Vargas Llosa turns the camera away from the group and focuses on the town and the culture of the town. In some ways, this feels like an even more reactionary move: the message seems to be something like -- the people of the highlands, there is something like ritualistic violence, paranoia, and madness built into their culture, and that this is perhaps where the Shining Path comes from. I don't know, that's where I ended up reading this. Loved it.
