---
title: "Lou Reed: The King of New York"
date: "2024-06-05"
author: "Juan Tellez"
categories:
  - books
  - biography
  - music
---

*Lou Reed: The King of New York* seems like the most complete biography of Lou Reed out there, covering his childhood, time with the Velvets, solo career, and his death in 2013.

A personal anecdote about Lou Reed: I went to graduate school imagining that I would do qualitative, deep history research on Colombia's armed conflict. Then I got there and all anyone wanted to talk about were coefficient estimates, standard errors, and natural experiments. I went through a crisis: is this really what I want to do? If I do it "their" way, am I selling out? If I do it "my way," will I not be able to write for a living at all? What do I even want to do, really?

I was in therapy at the time, both for grad school woes and for some difficult family dynamics. My therapist then laid out the story I would come to re-learn in this book: that Lou Reed starts out his music career writing songs for this strange record label, *Pickwick Records*. The company, interestingly, was proto-AI slop: they would hire musicians to quickly and cheaply write a ton of songs about specific themes (e.g., songs about going to the beach; Reed famously wrote a "do the dance" song called "Ostrich"). So the story goes, the payments from writing this garbage is what allowed Reed to live as a musician and eventually write some of the most influential rock music of all time. So the lesson is something like: you can be practical and still true to yourself, whatever that is.

It is interesting in the book that Lou does not sweat this at all; there is no crisis of legitimacy, "am I a sell out," etc. It is clear he sees working for Pickwick as practical and not a reflection of him as a person. This ethos continued throughout his life as he licensed his music / persona for commercials (clearly influenced by Warhol in this regard as well): having his songs appear in a Ford commercial or whatever is fine if it lets him finance his weird, commercially unviable rock albums. The experience also turned out to be useful to Reed: the Pickwick workflow of putting music out at inhuman speeds came in handy for the Velvets, who were operating on shoestring budgets. Note: they actually recently released his Pickwick-era music as a standalone album.

Anecdote aside, my exposure to Reed was through the Velvets, a band that made a huge impression on me as a teenager, drawn to the band's experimental sound and "edgy" lyrics. I still remember hearing the song "Heroin" for the first time and being blown away by the droning viola, the drumming, Lou's delivery, and of course the vivid lyrics about shooting up. I would eventually make my way through the band's other albums and fell in love with the music. Even today, it is still in heavy rotation at the house.

Given this exposure, one of the more surprising things about the book is how short-lived and unsuccessful the Velvet Underground's tenure was. Shorter still once you realize that Lou kicks John Cale out of the band after *White Light/White Heat*, meaning that what for a long time had been my favorite album (the self-titled LP) was not, really, a fully VU record.

One of the things you want out of a biography is a sense of the historical figure as a person. The view that emerges of Lou is a pretty unflattering one. He is controlling and nasty to people around him, both near and distant; you have the fallout with Andy Warhol which, from Warhol's diaries, we can tell was extremely painful (and needlessly so). There is also berating of service staff of all kinds, both during his chaotic years of addiction *and* his post-sobriety-ish, Tai Chi master, later period. He is painfully thin-skinned, calculating, someone who frets about how much others are getting (relative to him), where he is in the pecking order, how others perceive him, etc.

These latter qualities might produce someone who is always trying to do whatever is "in" at the moment, without much vision or sense of organic direction. But this is not true of Lou, which in the end is one of the most touching elements of the biography. There are all these tensions in Lou, maybe between his person and the character he plays on the records. Lou was insanely prolific, even publishing a photography book late in life, a quality that runs counter to the desire to protect one's image. His solo music, perhaps the only exception being the excellent *Transformer*, is also almost invariably out of step with the times, deeply uncool. Too many examples to point out: the Edgar Allan Poe album, the over-the-top edgelord lyrics ("Harry's Circumcision"), and of course the infamous last album with the deeply uncool Metallica. Whatever you say about him, he clearly had vision and passion, which I found inspiring.

The last chapter, detailing his relationship with Laurie Anderson and his death, was unexpectedly touching. Here is a man who has "done everything" and, in the twilight of his life, throws himself into a new relationship, martial arts, and Tai Chi (shout out to the song "Lou Reed" by Cory Hanson). Basically: there is always more life to live. Whatever corner you painted yourself into, whatever constraints you imagine on yourself, you can always do something new.
