---
title: "Making Empire"
date: "2024-06-05"
author: "Juan Tellez"
categories:
  - books
  - history
  - ireland
---

I was disappointed by this book or, at least, I had the wrong expectations going into it. I picked it up after hearing the author on *Empire Pod*, imagining something more accessible about the history of early English imperialism in Ireland. But the book is very "academic," and the acknowledgments indicate it is based on lectures the author gave in university. There's a frustrating level of detail throughout, at times giving way too little background on proper noun characters and at others focusing much too narrowly on individual people / towns. All to say, I didn't get all that much out of reading this.

Here's what I found interesting: the idea that Ireland is the "first" British colony, the only colonized country in western Europe; the steps the English took to try to "anglicize" Ireland early on; the process of using both settlers ("plantations") to dispossess the locals *and* (interestingly) the "carrot" of being made nobility to win over the elites; and the way that colonial practices in Ireland would later be reflected in other colonies, down to specific people (one Irish man who worked in colonial policing in Ireland, India, and Palestine). The Irish being sent all over the world was also surprising, but makes sense; that's *kind of* how you get the hilariously named Bernardo O'Higgins as a Chilean founding father.

These are interesting ideas but they don't get a lot of development; we move through them too quickly. There's also an emphasis on culture and discourse that I know is interesting to some people, but not to me. That colonial administrators in Ireland would conceptualize the island's "problems" in disease-like language, and that this same language would later show up in India, is not so interesting to me. What I found more interesting was how often the Irish were invoked in North America: "the wild Irish and the Indian do not much differ." There's a dark comedy there where the colonizer recognizes these "similarities" in otherwise very dissimilar peoples but fails to recognize the common denominator (the colonial relationship).

Anyway, wrong level of detail for most readers. Pass on this one.
