---
title: "Mason & Dixon"
date: "2024-06-05"
author: "Juan Tellez"
categories:
  - books
  - fiction
  - usa
---

In college (or was it grad school?) my now wife and I went to India with another couple. We took trains all the way from Mumbai to Dharamshala, and part of the way back. On those long train rides (20+ hours) with nothing else to do, no phones, etc., I read *Gravity's Rainbow* and was blown away.

Not only had I never read anything like it before, I also feel it broadened my ability to read and my appetite for difficult books. One: to focus less on the internal logic of the story and more on the meaning of the writing; in all his books, Pynchon is riffing and improvising and just doing crazy jazz shit with language. Two: to be OK with losing the thread of the story, getting lost, or turning to secondary sources to figure out what the hell is going on. I think for most people, that experience of getting lost triggers a defensive reaction: if there is no grand plan for the plot or the prose, then this is pointless, like hearing someone press random keys on a piano. But just as with improvisational music, the whole point is the musician/author's ability to dance on that line between unintelligible noise and something sublime.

That said, *Mason & Dixon* beat me. An absolute slog to get through. The plot itself is way too thin, the prose too obtuse, and the time period not one I am familiar enough with to really feel like I had my bearings. Maybe it's unfortunate timing -- I started reading this a few weeks prior to my daughter's birth, and then finished in the following months, sleep deprived, starving for entertainment. Maybe not a great time for difficult books.

There are a few standout moments. Surprisingly enough, as much as I wanted them to get to America already, my favorite parts of the book are in the earlier sections, when they're in South Africa and sailing. And then towards the end, the Hollow Earth stuff was interesting. But the story within the story felt tedious and too little "happens" while they're in America to make the juice worth the squeeze.
