---
title: "Maus"
date: "2024-03-21"
author: "Juan Tellez"
categories:
  - books
  - memoir
  - graphic-novel
---

I've only read a few graphic novels and I can't say I ever "got" the value of the form. Reading a graphic novel mostly felt like reading a pretty short story, with some visuals I might stop to look at sometimes, but that don't add so much to the story. Reading *Maus* made me think I'm probably wrong about all of this.

This book is really a masterpiece. The narrative is so rich, it's hard to know where to begin. The book has this meta-fictional quality in that you follow *the author as he writes Maus*, which is about his parents' experiences in Auschwitz. We see the author spend time with his father, their difficult relationship, and at points the father narrates to his son his experiences in the Holocaust, at the behest of the author, so he can write his book.

A central theme, given this framing device, is how the past haunts the present. We see the father and son driving back from the grocery store, and are then transported to the camps as the father shares more of his memories. But I think it is also clearly about how the horrors of the world are happening all the time, while we are driving to work, buying groceries, etc. This is just part of life, something we don't like to think about, but *Maus* squeezes it all together in these extremely dense pages.

The fact that the narrative follows the son as he writes the book adds this intensity and sort of "unspoken knowingness" to everything we see on the pages. The son is frustrated by his father and frequently criticizes him, but as readers we know that many of the behaviors the son finds so irritable can be linked to his experiences in the camps -- his intense frugality, resourcefulness, desire for predictability. And we know that the son knows this too, obviously, which makes his relationship with his father rich and painful to read about. The guilt the author feels is palpable in every interaction with the father.

Also interesting is that the father's narrative of the Holocaust is laid out in the form of memories, which are not fully reliable, yet feel true regardless. The son at certain points questions the sequence of his father's story (e.g., "how could you have been at X for Y months when you were in Z at Y-1"). And the interpretation of the father's "packrat" behaviors as a legacy of the Holocaust, which seems so clear, is also questioned by his second wife, who says something along the lines of "I know other survivors, and they are not like this."

Could probably go on and on about this. I have consumed a lot of content about the Holocaust but none have made me feel the emotional dimension of the brutality like this book. The father's losses are inconceivable. That they lost their first child to the camps is inconceivable. That his wife survived the camps to commit suicide decades later is inconceivable. The final page of this book hits you like a ton of bricks.

I read "The Shadow of a Past Time: History and Graphic Representation in Maus" at Andrew's suggestion (he also suggested *Maus*) and I thought it was super illuminating.
