---
title: "My Name Is Red"
date: "2025-07-30"
author: "Juan Tellez"
categories:
  - books
  - turkey
  - fiction
---

*My Name Is Red* is Orhan Pamuk's best-known book, at least in the West. Pamuk is also Turkey's best-known fiction writer, at least in the West. So this is Turkish fiction 101; something like picking up Marquez as a first stab at Colombian (or even Latin American) fiction. I wanted to read this after listening to the excellent Empire podcast on the Ottoman Empire. I also picked up *The Ottomans*, which is still sitting on my bookshelf.

The story follows a group of miniaturists -- an art form based on embroidering texts with depictions of historical events, battles, etc. -- in the late 1500s Ottoman Empire as they grapple with their changing art form and the mysterious murder of two of their members. The story is told in a relational style: each chapter is a character relating events to the reader, who is at the same time placed in the position of some unidentified third party that exists in the story.

The most straightforward read of the book is as an allegory for Turkey's unique place in the world, a country that straddles "east" and "west." Pamuk's miniaturists are consumed with anxieties about the seeping of "Frankish" style (i.e., Western Renaissance art) into their art form. The discussion of the differences in style are some of the most interesting parts of the novel. The miniaturists, for instance, are especially troubled by the use of perspective in Frankish art, which they perceive as a kind of idolatry. Their traditional art form instead "lacks" perspective, imagining itself as presenting the world as Allah sees it: trees, dogs, buildings, people, all the same size, flattened in some sense.

Part of the reason they are anxious about these new forms they are coming into contact with is that there is something alluring about them. This is key to the allegory, in my opinion: it is not the case that the western forms are being exogenously imposed on Ottoman artists. At this point, in fact, the Ottoman Empire is arguably at the peak of its power. Rather, there is something innately alluring about Western art, especially portraiture, which Ottoman leaders (the Sultan) instinctively find appealing because of its grandiosity and projection of power.

This ambiguity is where I think Pamuk keeps the reader for most of the novel. We should find something distressing about the encroachment of Western art, the loss of these indigenous art forms. But we should also probably be disturbed by the orthodox, puritanical rejection of those who burn down the storyteller's tavern at the end of the book.

Parallel to all this interesting fodder is an epic love triangle romance with great characters, world-building, dialogue, etc. This is peak historical fiction.
