---
title: "My Year of Rest and Relaxation"
date: "2024-09-14"
author: "Juan Tellez"
categories:
  - books
  - fiction
  - usa
---

*My Year of Rest and Relaxation* follows the narrator, a young woman who decides to take an insane concoction of pharmaceuticals every day to... it's not exactly clear for what; she says it's to sleep.

Damn, this is some of the best fiction I've read in years. It's really fucking funny. She captures this kind of modern person who is an adult but very much reads like a "girl" and not a "woman." It reminds me a lot of *American Psycho*, but whereas Bret Easton Ellis claims the book is a satire (he's obviously lying) this one feels more honest.

To me the narrator feels like someone who has fallen out of the social fabric, and the sense I get is that Moshfegh is trying to say this is a generational thing. This kind of permanent adolescence, but also that she's someone who is no longer inscribed in educated, liberal politics — she says things that are offensive, thinks about race in a way she's not supposed to, about beauty and weight in ways she's not supposed to, etc.

Reading it, I can't help but make comparisons to the Red Scare podcast. I'd like to think the narrator is better than them, or more redeeming somehow, but I'm not sure. The edginess in this book can feel empty and ugly in the same way, but Moshfegh is such a good writer that you let it slide.

Always impressed by writers who can entertain you with little plot to lean on.
