---
title: "Nights at the Circus"
date: "2024-12-19"
author: "Juan Tellez"
categories:
  - books
  - fiction
  - uk
---

*Nights at the Circus* follows a reporter, Jack Walser, as he covers an acrobat named "Fevvers" who is famous for being part woman, part bird. The book is structured in three parts: in London where they first meet; in St. Petersburg, where they both join a circus; and then in Siberia, where they are stranded after their circus train derails. It is a wild tale, cartoonish at times.

On paper, this book is not "my thing." It's got elements of magical realism / fantasy that feel fanciful and cutesy in ways that I mostly find annoying. But I was really impressed by some parts of this book; I'd say parts 2 and especially 3 are really strong. Carter spins out an impressive array of characters, great scenes (loved the Buffo the clown content), and she's playing with the genre in ways that feel fresh. Fevvers gets a lot of screen time but she doesn't get stale; Carter is able to wring out depth as the book advances.

I can't say that I know what this book is trying to "say." Carter is clearly preoccupied with gender, with women's roles in society, with a kind of power/curse that is allotted to women as a function of their being seen and desired. Fevvers clearly has power, can maneuver and manipulate men effectively, as do many of the other women in the book. But she is also dependent on Walser, being seen by him:

> And surely he was here; one of the wooden houses must shelter the young American. And she would see, once again, the wonder in the eyes of the beloved and become whole. Already she felt more blonde.

There's also something here about time: the turn of the 20th century is constantly referenced, especially towards the end of the book. There's maybe an (unfulfilled) expectation that the 20th century will bring about women's liberation, or something broader:

> 'And once the old world has turned on its axle so that the new dawn can dawn, then, ah, then! all the women will have wings, the same as I. This young woman in my arms, whom we found tied hand and foot with the grisly bonds of ritual, will suffer no more of it; she will tear off her mind forg'd manacles, will rise up and fly away. The doll' house doors will open, the brothels will spill forth their prisoners, the cages, gilded or otherwise, all over the world, in every land, will let forth their inmates singing together the dawn chorus of the new, the transformed --'

But this sounded odd to me coming out of Fevvers's mouth. I feel as though I'm missing something about the importance of this transition.
