---
title: "Paul: A Biography"
date: "2026-02-20"
author: "Juan Tellez"
categories:
  - books
  - biography
  - religion
---

I was baptized, had my first communion, and went through confirmation, but I had no idea Jesus had a brother (James). In fact, my background in Christian history is basically nonexistent in spite of all that religious education. What gives? I knew nothing of Paul before reading this book, save for his letters.

Now I know more, sort of. The author makes clear that what we can know with confidence about Paul is very limited. We are not even sure how or where he died. The book is also written with a probably more religious or theological audience in mind; it dives into interpretations and debates about Paul's work and beliefs that I mostly glazed over.

But it is a fascinating story. Paul is essentially torn between two worlds: the Jewish world, of which he was a devout follower (he was a Pharisee), and the Christian world that he was helping to create. As is well known, Paul in fact worked with the Romans to repress early Christianity, seeing it as a threat to Judaism. As the story goes, while on the road to Damascus to continue this "work," he experiences a blinding light that leaves him incapacitated for three days. When he recovers, he is converted into the Apostle that Christians know today.

Much of the biography follows Paul as he works to set up the early Christian church around Asia Minor, and the challenges he experiences in the process. At some point he is beaten and stoned; at another there is a gap in his life that the author argues was a likely stint in prison.

As I understood it, the key problem Paul faced is that even among the Jewish communities who were open to the idea of Jesus as a messianic figure, there was a great deal of resistance to opening the faith to gentiles (non-Jews). His opponents believed that, whatever this new faith was, they should still adhere to Judaic law, especially (surprising to me) circumcision. Paul wanted what we might call today a more "universal" faith, such that members did not need to adhere to these practices. Some of his letters are about this (especially Galatians).

Overall, interesting but too long on the content of Paul's beliefs and ideas, and less on the politics and social dynamics of the time.
