---
title: "The People Immortal"
date: "2024-03-21"
author: "Juan Tellez"
categories:
  - books
  - fiction
  - ww2
  - europe
  - soviet union
  - russia
---

*The People Immortal* follows a group of Soviet soldiers fighting an invading Nazi army. The situation is pretty dire; the Nazis are in Soviet territory (primarily in Ukraine), they are rampaging through civilian towns, and things do not seem to be going well. Reading descriptions of the book I imagined an almost suicidal last stand on the part of the Soviet troops. But that's not how it goes; in the end, the Soviets are victorious in a way that feels a little flat.

There's some interesting stuff here. The civilian perspective on what an invading army looks and feels like is compelling. German troops are coming into their villages, people are deciding whether to flee, there's the drama surrounding the one local who decided to collaborate with the Germans for opportunistic gain, Kalyvas-style -- it's all great. It gives you a clear sense of what it *means* for a country to be invaded. From 10,000 feet up, you might wonder why a civilian in some random town would care whether some person who doesn't care about them is in charge or whether some foreign government comes in and installs a different person that doesn't care about them. But here you get a clear sense that an invading army is basically torching everything as it goes.

The soldiers' ideology and their perspective on the Germans is also interesting. The ideology part can feel ham-fisted at times. Long, mostly awkward descriptions of the Germans failing to grasp the "natural law" of Marxism or whatever makes the book feel like propaganda. My version of the book highlights many moments where the author or publisher self-censors. It's not clear you're getting it totally straight. Still, it would be crazy to think at least some people, especially soldiers, didn't fully believe. There are some beautiful passages towards the end where the author sees the Soviet mission as being about "humanity's eternal longing for a land that does not know slavery."

The Soviet soldiers we follow *really* hate the Germans, which I also found very interesting. There's this titanic struggle between Communism and Fascism but the soldiers don't grasp any of that. They primarily see the Germans as innately mechanical, soulless, too organized, etc. There are a bunch of these passages, but here's one:

> "...In their capacity for mechanical obedience, in their readiness to march on mindlessly, in the ability of millions of soldiers to execute huge and complex manoeuvres with iron discipline -- in all this there was something base, something foreign to the free spirit of man. Rather than being a cultivation of reason, this was a harnessing of instincts, a form of organization similar to that of ants and herd animals."

There's obviously plenty of fiction and non-fiction that is "critical" of the Nazis, but it is about the Nazis as such, and not the Germans. These soldiers hate Nazis too, but they also hate the Germans. It's not often you get this kind of "Otherized" view of the Germans during the war.

Overall, a decent read. Some parts feel a bit too close to "glorious war for the homeland" propaganda. I'm more partial to *Generation Kill*-flavored war books.
