---
title: "Putin"
date: "2023-11-21"
author: "Juan Tellez"
categories:
  - books
  - history
  - soviet union
  - russia
---

The start is impressive in its detail but at some point the original sources seem to disappear and you get a view of Putin from very far away. I still feel that I learned a lot. The big stand out moments were 1) seeing the collapse through Putin and his generation's eyes; 2) the scale of the terror emanating from Chechnya which I had no sense for; 3) the importance of NATO intervention in Kosovo from the Russian side of things.

The book has been criticized for being overly sympathetic to Putin and towards the end I tended to agree. Everything seemed a little too "neat", where Putin just wanted to cooperate but the US wouldn't have it. Personally, I don't mind reading a book that is sympathetic to Putin. It's a fresh perspective. But Short seems to have strong ideological stance against "the Blob" / the hawk wing of American foreign policy and that colors how he views Putin and his actions quite a bit. In the end I kept coming back to: the Soviet Union collapsed and the United States, rather than leave everything as is, or make some grand gesture of cooperation, pushed for advantage. Would Russia have done differently had the shoe been on the other foot?
