---
title: "Quantum Criminals"
date: "2024-06-05"
author: "Juan Tellez"
categories:
  - books
  - biography
  - music
---

This book feels like it was written with me in mind. *Quantum Criminals* is not a biography; it's a series of essays on Steely Dan, each using a specific song (in chronological order) from their catalog as a jumping-off point to talk about their influences, approach, the lyrics, and Donald and Walter. I *loved* this format: read a chapter, catch what song they are discussing, pop that on, back to the book. I would happily read more books like this, especially about bands that I've struggled to "get."

More than the format, though, the way the authors frame Steely Dan's status in the culture captures how I felt about the band. For people my age growing up on indie rock bands that emphasized a sincere, lo-fi / low-effort authenticity, the glossy sound of Steely Dan and other 70s soft rock reads as fake, overly produced, a put-on. Of course, as you get older, you realize that making sure everyone's wearing flannel, or having songs that start with someone plugging a guitar into a hot amp, or that contain studio chatter, or where the drummer counts them in, are no less of a put-on. These are all choices being made deliberately to convey a specific aesthetic.

With the Dan / yacht rock renaissance I've come to appreciate their music more, although I still wonder to what extent my enjoyment is sincere. That said, they have undeniable bangers. "Peg" might still be my favorite; reminds me of Mario Kart music. And lyrically what they are doing is much more complex than I realized, more in the Dylan vein of songwriting.

Would recommend the behind-the-album documentary on YouTube about *Aja* to pair with this book.
