---
title: "Right-Wing Women"
date: "2024-06-05"
author: "Juan Tellez"
categories:
  - books
  - philosophy
---

*Right-Wing Women* is billed as an analysis of women on the right by the iconic, firebrand feminist Andrea Dworkin. The book is actually much broader than that, also delving into Dworkin's broader feminist framework, social value in a gendered society, abortion, reproductive technologies, and so on.

I'd heard of Dworkin before, mostly through her opposition to pornography and the often-referred-to claim that all heterosexual sex is coercive given steep imbalances of power between men and women. This was my first time reading her writing directly.

If I had to describe the style of her writing, I would say it almost feels as though she is rapping or freestyling. She's making big claims, even if she doesn't elaborate them; she is machine-gunning ideas; she is sarcastic, angry, funny; when she's really going, I'm all in.

Her style really works in the first, standout chapter, "The Promise of the Ultra-Right," and the chapter on abortion. Her take on right-wing women is that they, like left-wing feminists, are acutely aware of the violence and domination that is inherent to relationships with men, and so seek a compromised safety in marriage and control over reproduction via opposition to abortion. As Dworkin writes, "the Right promises to put enforceable constraints on male aggression, thus simplifying survival for women." She analyzes specific anti-feminist women of the era, whom I had known little about and found fascinating. Phyllis Schlafly being a war hawk in her origins but pivoting to women's social issues because that's all the rope the GOP would give her was interesting.

Dworkin's takedown of the hippie movement and the counterculture in the abortion chapter is particularly brutal and effective, maybe the best part of the book: "[sexual liberation] did not free women. Its purpose -- it turned out -- was to free men to use women without bourgeois constraints." Here she is writing directly from experience about the abuse and dismissive treatment of women in the radical organizations of this period.

Aside from this one chapter, however, her style falls apart. The rest of the book is truly a slog. The writing is just *so* repetitive, and I mean that literally; she repeats sentences, for rhetorical effect no doubt, and I could imagine a speech where the repetition works. But not as a book. The content is also less interesting later on, amorphous. The most precise claim in the latter half of the book is in the chapter on Christianity, where she makes the odd claim that homophobia is unique to the New Testament and that in the Old Testament, whatever prohibitions were in place, were in some broad sense perhaps more tolerant. It's an odd piece.

It would be interesting to know what Dworkin would say about the world today.
