---
title: "Social Movements and Civil War"
date: "2026-01-20"
author: "Juan Tellez"
categories:
  - books
  - protest
  - war
---

This is an edited volume on the role of social movements in civil wars, by the influential Italian sociologist Donatella della Porta. It consists of an opening chapter laying out some persistent themes in the evolution of "peaceful" social movements into armed conflicts, followed by case study chapters on the protests leading up to the Syrian civil war, the fall of Gaddafi in Libya, protests in Yemen, and the dissolution of Yugoslavia.

This was more of a skim than a read on my part, as it's pretty tedious. The main theoretical chapter reads more like a shortened version of a textbook on the causes of conflict and protest than something original. Della Porta highlights some themes (too many, in my opinion), of which the most memorable are the fragmentation of social movements in response to exogenous shocks and the internationalization of conflicts. The others seem like boilerplate.

The case study chapters are also a mixed bag. The Syria chapter is OK. One interesting puzzle is that Islamist groups (ultimately the most successful movements in the Syrian civil war) have on the one hand broad appeal (given religion) and yet also tend to have highly sectarian tendencies. Sectarianism in general is really interesting to me. If what you want to do is defeat a sitting ruler who is vastly stronger, why dedicate time and resources to targeting other sects (e.g., ISIS targeting of Shi'a and other minorities)? One explanation is that that's just what they believe, but this is unsatisfying.

The Yugoslavia chapter is very interesting, perhaps because I know so little about it. I didn't know, for instance, that Yugoslavia itself was designed in such a way as to keep the various nationalities under the same roof. It reminded me of the paper I'm finishing on Ethiopia and how the TPLF undertook ethnic federalism to contain separatist elements. I did not know Yugoslavia was arguably further along the path of ethnic federalism than Ethiopia, with each republic having its own security forces. The Syria chapter also surprised me in showing that, early on, Assad (son) was a bit of a reformer and liberalizer, which reminded me of the other paper I'm writing on Abiy Ahmed.

The chapters on Libya and Yemen are forgettable.
