---
title: "A Stranger in Your Own City"
date: "2024-06-05"
author: "Juan Tellez"
categories:
  - books
  - iraq
  - history
---

*A Stranger in Your Own City* is sort of a journalist's diary, like Cockburn's books, but more personal because the author is from Baghdad and has an incredible story of being swept up into journalism by the war. The book is expansive, beginning with the Iran-Iraq war and going through the US invasion, the subsequent civil wars, the rise of ISIS, and ending with the mass protests of the late 2010s.

This is easily one of the best books about life in a war zone that I've read. The author is a talented writer and saw and immersed himself in events that are hard to believe. He captures so many elements of these conflicts, and then there are these off-the-path chapters that are also incredible, like the one charting the migration of Syrians and Iraqis through Greece and (hopefully) into Germany.

In my view, where the book is best is in how it captures the sectarian nature of the civil wars that followed the US invasion. Baghdad was a mixed city, where inter-sect relations were mundane, if not common (though I wonder to what extent this was also true in rural areas?). The war unleashes an almost textbook "ethnic security dilemma" where Shi'a and Sunni arm themselves to the teeth and engage in tit-for-tat escalations that ultimately cleanse the city of Sunni inhabitants. Seeing ISIS emerge with this perspective in the background was very interesting.

Much respect to the author; this is incredible, inspiring work.
