---
title: "Temporada de huracanes"
date: "2024-10-27"
author: "Juan Tellez"
categories:
  - books
  - mexico
  - fiction
---

*Temporada de Huracanes* is a novel about a poor Mexican town where a "witch" is murdered. Each chapter follows the viewpoint of a different character (almost all kids) and their lives in this fucked-up town.

Bolano's *2666* feels like a close cousin to this book, not just the themes but the style of the writing. There are no paragraphs, barely any periods, just sentence after sentence separated by commas. The feeling is of hearing someone who is at times out of breath (or maybe fucked up on drugs) tell you the story of this town. The writing lands hard and can feel suffocating at times. I felt relieved when a chapter came to an end.

The story itself is so dark that I felt it ran the risk of cheapening the book, but by the end I was convinced this was not the case. There is an extended description of child abuse near the middle of the book that almost led me to put the book down entirely. And then somehow in the last 20% of the book the author also writes about a variety of sexual assaults, bestiality, and a late-term abortion.

The moral nihilism with which the characters (again, almost all kids) approach these issues reminded me of the movie *Kids* and some of Harmony Korine's movies. They make the same kind of move: let's follow these kids in these objectively horrible situations characterized by poverty, drug abuse, social disorder, etc. But rather than tell a nice, "leftist" story about how these kids have hearts of gold, or are trapped entirely by their circumstances, or are making totally rational (if ugly) choices in an immoral world, what the book tells us about the interiority of these kids is mostly not good. There is a deep, antisocial pathology in their worldview (especially Brando), with some exceptions.

While this move can be effective in adding a layer of realism to the storytelling (after all, why *wouldn't* living in these conditions produce a kind of antisocial nihilism?) there is also something that can feel reactionary and ugly about painting life in this way. The final chapter of the book lets the reader rest and pulls back from the horror we've been seeing for 200 pages, so in the end I would say it works.

Part of what's interesting about this book too is that it upends a binary way that people think about life in urban, cosmopolitan capitals and rural, peripheral towns in the developing world. There's this view that life in rural areas is more traditional, more orderly, less licentious, etc., than urban life, even though this comes at the "cost" of higher poverty, lower quality of life, etc. This book convincingly shows us no, actually: disorder can also be the norm in these kinds of communities, "poverty" (though it's much more than that) *can* corrupt the soul of otherwise good people.
