---
title: "The Ottomans"
date: "2024-06-05"
author: "Juan Tellez"
categories:
  - books
  - history
  - turkey
---

I heard about this book on the Fall of the Ottoman Empire podcast. I was inspired to read it after finishing *My Name Is Red* but also from realizing how many people I know from Turkey.

This is an accessible history of the Ottoman Empire going back to the 14th century. This was an enormous empire that at one point was stronger than any European country and that stood out for its "pluralistic" way of governing, but that eventually collapsed and turned to genocidal purges of its ethnic minorities. I learned a lot from reading it and have a clearer sense now for contemporary Turkey's relations to its neighbors. I have to say that I honestly struggle to care about world history pre-17th, maybe even 18th century, so I wish this book had leaned more in the direction of the present. I'll highlight some interesting anecdotes:

- The fact that the Ottoman Empire did not use a primogeniture rule to determine succession of the Sultanate. Instead, there was typically a battle amongst the male heirs to kill or exile the others and take control of the Empire. As an institution, this is very interesting. On the one hand, obvious chaos and bloodshed at the point of succession, both of which are much less common in kingdoms with primogeniture. On the other, the all-out melee could be sorting for people who are better leaders and warriors.
- The Ottoman Empire's connections to the Roman Empire, and the fact that some viewed the Empire as a succession of Rome, was interesting. In general Baer is imploring readers to see Ottomans as part of European history, not something else.
- The numerous discussions of pederasty were truly vile; I almost felt sick at different points. I understand that this is more widespread than most want to admit but still upsetting to read -- historical relativism does not appeal to me.
- Some of the earliest points of contact between Ottomans and England is the latter trying to get the former to ally against Spain. Interestingly, part of the pitch was that both societies rejected "idolatry" (the English as Protestants, the Ottomans as Muslims) which I found funny. How much stronger the Ottoman Empire was than England is seen in this great quote from the book: "When Murad III initially received Elizabeth I's letter, the Sultan had to examine a map to see precisely where England was located in geographical relation to his Mediterranean nemesis, Spain. Historian Dr. Cristine Woodhead of the University of Durham writes that when 'the English traveller Fynes Moryson recorded that when the Ottoman Sultan Murad III was shown the location of England on a map, he peered at it in astonishment and wondered aloud why the King of Spain did not take a spade, dig it up and throw it into the sea.'"
- Unsurprisingly, the 20th century, when the Empire unravels, the Armenian genocide, wars with Greece, the move from "we are Ottoman" to "we are Turks" -- all of this was most interesting to me. I should read a book just on this period.
