---
title: "Time Shelter"
date: "2024-03-04"
author: "Juan Tellez"
categories:
  - books
  - fiction
  - bulgaria
---

I read this for neighborhood book club.

*Time Shelter* mostly uses a loose plot about a psychiatrist building a kind of hyper-real, decade-specific amusement park to riff on memory: how some things can't be forgotten, others get memory-holed, and how in our current moment we seem obsessed with the past and nostalgia.

I'm not sure how well it all works. The nostalgia bits are the most interesting to me; it does seem true, in the way hipsters are now turning to Americana and psych rock, or the way Swift rereleases all her old albums. But the book was thin on that. It also felt like the author was trying too hard to be clever, with an editor in the background somewhere worried that the reader wouldn't get it. Lots of moments of a joke based on some allusion to a book or song, followed by a sentence explaining the allusion.

Something about new books is that they all kind of feel like they were written for a limited series TV show. This feels exactly like that. A lot of cute world building but it doesn't go much of anywhere.
