---
title: "Ubik"
date: "2024-04-02"
author: "Juan Tellez"
categories:
  - books
  - fiction
  - usa
  - sci-fi
---

*Ubik* is a novel that at first seems to be about a future where people with extrasensory powers battle on behalf of private corporations. But this is mostly a red herring. The story really turns on the fact that, in this future, people can keep their loved ones alive for exponentially long periods of time in a "half-life" state. The book's twist revolves around this half-life state.

I generally don't like sci-fi. I don't get anything out of the world building; "this isn't a story about humans on Earth, it's a story about Blingblongs from planet Worblorg — and they walk on the ceiling instead of the ground." Who cares? It's not like this is real! It's made up. Angler fish are crazy because they seem like aliens yet they are real. This made-up stuff is not that interesting.

*Ubik* is good because it mostly jettisons the sci-fi halfway through and turns into something closer to a horror novel. Joe Chip spends most of the latter half of the book drifting through this dream/nightmare world, at the center of which is this weird substance, Ubik, that can pierce through the haze.

Of course, you want to know what it all means, especially Ubik. Given Dick's other work and his background with drugs, it's hard not to read a drug allegory into the story, where the dreary dream-like world is reality and Ubik is the drug that cuts through. The other approach is to focus on the technology and how it mediates our interactions with the world, but that part seems less fleshed out.

The writing is impressive in parts and on the whole I liked this a lot.
