---
title: "Una historia política de Colombia"
date: "2024-03-21"
author: "Juan Tellez"
categories:
  - books
  - colombia
  - history
---

This is a book about Colombian history from about 1830 to about 1958. It's a strange book: some chapters are just one or two pages long. Two chapters have the same name and a fair amount of overlapping content. This is not a good book. But it covers a very interesting period of Colombian history.

You get the early divisions between the Conservative and Liberal parties and the long periods of first liberal hegemony, then conservative, then liberal. What seems to stand out about Colombia is the extent to which each party, once in power, prosecutes and uses violence against partisans of the other party. Some of this seems linked to the fact that virtually all government jobs were appointed by the incoming government, which meant massive transfers of employment in elections where the party in power changed.

The shifts from centralized rule to federalized rule are also interesting. I'm used to thinking about decentralization as a 1980s/1990s phenomenon, but here they are fighting about this in the 1800s. The major conflicts in the 19th century basically involve regional militias rising up against the central government and winning because the latter was so weak. I'd never thought about the fact that at some point Colombia was "the United States of Colombia."

I was on a reading roll and this book sapped the joy of reading out of me. Horribly written.
