---
title: "Vichy France"
date: "2024-06-05"
author: "Juan Tellez"
categories:
  - books
  - france
  - history
  - ww2
---

After the Nazis' shocking defeat of France in WW2, they split the country in half: the north occupied by the Nazis and the south under the control of a French "Vichy" government (named after the spa town of Vichy, where the government was headquartered) that collaborated with the Nazi regime. This book is a history of Vichy France, famous for arguing that Vichy France was eager to collaborate with the Nazis, an uncomfortable claim in France where the official narrative was closer to a reluctant, "slow walk" participation.

This is fascinating history in a book clearly aimed at academic historians. If you don't know who Pétain was before reading this book, Paxton is not going to tell you. I know very little about this period of French history, so I ended up skimming long portions that didn't feel useful to me.

Why did the French collaborate? For ordinary people, including many in the civil service, the core desire was a return to normalcy. WW1 was not even a generation away; there was little appetite for continued war. Many also expected the war would end soon with some kind of German victory. What the Nazis would do with France was not clear, but resistance seemed too costly to most and so was scarce. There's an incredible story about Simone de Beauvoir hitchhiking back to Paris (pg. 17), feeling relief at being able to teach at the lycée again, not concerned about having to swear an oath to Pétain in the process.

At the elite level, collaboration was more active. Elites of various ideological stripes interpreted France's loss as a sign of the need for some kind of domestic revolution, that France had fallen to "decadence" (Ross Douthat!). The Vichy leadership imagined promoting a National Revolution that would reconfigure French society; they imagined working with Hitler so that France held some space in the new German European order; they imagined Germany protecting French colonies from British expansion (an incredible thing to worry about while occupied by a foreign army). What's most incredible is that, for the most part, Hitler was not interested: "Collaboration was not a German demand which some Frenchmen acceded, through sympathy or guile. Collaboration was a French proposal that Hitler ultimately rejected" (51).

Vichy actively participated in antisemitic (especially deportations) and anti-Masonic policy. Most shocking to me, there was even direct combat between American forces and French Vichy forces as the former invaded North Africa. French soldiers killing American soldiers on behalf of Germany: I had no idea this had happened.

I would have loved to see more discussion of everyday collaboration. Paxton largely splits French society into regular people, who just did their jobs and went about their lives, and elites, who saw Vichy as an opportunity for restructuring French society.
