---
title: "Vineland"
date: "2024-06-05"
author: "Juan Tellez"
categories:
  - books
  - fiction
  - usa
---

Pynchon's books feel like they are either about the plot or about the writing: at one extreme he is doing insane free-jazz shit with language, and at the other it's paint-by-numbers storytelling. If *Mason & Dixon* is closer to the free-jazz extreme, *Vineland* is closer to a plain vanilla story, at least by Pynchonian standards. Unsurprisingly, I liked it much better than *Mason & Dixon*. It has a lot of similarities to *Inherent Vice* but is nowhere near as funny or engaging (I liked *Inherent Vice* better).

What makes *Vineland* stand out in its own right is Frenesi, a (former?) radical and mother who shocks everyone by falling for the fed (Brock Vond) who is on her tail and, in the process, abandons her daughter and partner. *Vineland* is a world of radicals whose time has passed, who have compromised, where movements are disintegrating, and it is not clear what, at the time the book is set, comes next. We see this through the eyes of Prairie, Frenesi's daughter, for whom this world of radical/hippie/counterculture is already largely the prior generation's thing, something in the past but also marked by betrayal.

What's interesting about the world Pynchon sets up is that it is not so clear *why* this has happened, just as it is never clear why Frenesi falls for Vond. It is (in my view) *not* the case that the feds simply dismantled all these movements, that this is a story about successful, violent counter-revolution. Something more subtle happened, more organic, a kind of drift. The Tube certainly has something to do with it, the commodification of the counter-culture through (among other things) rock-and-roll and consumerism. But again, I don't think it's the simple, '60s burnout theory of "they brainwashed us." It is more as though the Tube picked up on something that was already there, a sort of tendency towards conformism. Besides all that, I found Prairie and Zoyd's relationship very sweet.

Looking forward to seeing what PTA did with this.
