---
title: "The Wages of Destruction"
date: "2024-06-05"
author: "Juan Tellez"
categories:
  - books
  - ww2
  - economics
  - history
---

Now this is why we get up in the morning. What a great book. Something noteworthy: in the introduction, Tooze writes that he will not lay out the book's core conclusions, because this would spoil the process of reading it. What an idea! Meanwhile, the average political science book has an introduction that gives you a painful outline of the book and what each chapter does; each chapter then begins by outlining itself and concludes by summarizing. How much of these books is just a summary of itself?

I was intimidated by the book but Tooze is simply a great writer and makes the whole thing come alive. It is essentially a history of WW2 from the German perspective, with an emphasis on how economic resources (or material conditions) shaped the behavior and choices of the Nazis during the war.

This book in some ways runs counter to the way WW2 is typically taught in American high schools, which emphasizes Nazi ideology and Hitler's singular desire to "conquer the world." Tooze does not wholesale invalidate this telling; in fact, he explicitly and convincingly argues for the role of ideology in German behavior. But the picture he paints of the German war effort is one of choices constrained by economic forces.

For instance, the reparations imposed on Germany after WW1 are famously onerous because of how they coincided with the Great Depression. The Germans were having to make payments in foreign currency at a time when the major world economies were turning inward through protectionism, meaning there was nowhere for German exports to go in exchange for foreign currency. Among other things, this taught Hitler that Germany must secure its own resources to survive a serious contest against Britain and the US.

The US itself looms very large in Hitler's thinking. He and other Nazis were fixated on US manufacturing — particularly the auto industry — whose scale they saw as a function of the country's size, which gave it access to ample natural resources and a large enough population to sustain domestic demand for manufacturing. Hitler saw the necessity of acquiring resources and growing the German population through a "settling" of the East, analogous to US frontier expansion to its West.

These economic considerations also help explain why Hitler decided to invade the Soviet Union, another moment which US history classrooms usually treat as a kind of folly or "madman" decision. Tooze argues for a parallel between Germany's shocking defeat of France and the war on the Eastern Front against the Soviet Union. Both were driven by the knowledge that Germany did not have the resources to win a long war against Britain, France, and especially the US. The Germans knew in both instances that if they did not defeat their foe quickly, the war would be lost. They were thus high-risk gambles that succeeded in France but failed in the Soviet Union, and only because Stalin was able to generate obscene amounts of industrial production in such a short time span.

The book is written with great passion and full of incredible details. Highly recommend.
