---
title: "War in the Age of Trump"
date: "2024-06-05"
author: "Juan Tellez"
categories:
  - books
  - history
  - war
  - syria
---

I listened to this on audiobook and learned that, mercifully, the "ck" in the author's last name is silent. This will definitely make it easier to discuss his books in my classes.

I loved his last book, *Age of Jihad*, and have used it in my classes. I was also more familiar with the time period that book covers — starting with the US invasion and onto the emergence of ISIS — than the period covered here. That might be one reason why I didn't enjoy it as much.

The other reason is that Cockburn's ideological viewpoint — anti-imperial, reminiscent of the views you get from The Intercept, Radio War Nerd, that crowd — was less heavy in the first book than in this one. That's probably because the anti-imperial take on the wars in Iraq and Afghanistan is pretty vanilla, closer to the norm. But with the war in Syria, the anti-imperial crowd went off in weird directions, taking the "if a country/group confronts the USA/West then that's anti-imperial and therefore good" logic to incredible conclusions.

Chapter 3 was probably my favorite. It covers al-Baghdadi's disastrous rule over ISIS from 2014 onwards. It's an interesting case study of ideology leading to suboptimal behavior: at first, the Kurds stay neutral on ISIS, using the jihadis' conflict with the central government as an opportunity to grow Kurdish holdings. But ISIS attacks the Kurds in Syria, turning them against ISIS and ultimately linking them to the US. This was seemingly done because al-Baghdadi viewed everyone as an enemy, at least partially on religious/sectarian grounds.

Other notes: the format of his books is interesting. There are parts that are pure war diary/war correspondent (and these are a treasure), and usually the leading chunk of each section is Cockburn's post-hoc analysis. A funny thing about reading this book now is that Cockburn's intense conviction that the US and their allies are on a fool's errand, that Assad would not fall to some ragtag jihadis, looks silly now that we know he does in fact fall to such a group. The future is hard to predict!
