---
title: "The White Guard"
date: "2024-06-05"
author: "Juan Tellez"
categories:
  - books
  - fiction
  - russia
  - ukraine
  - war
---

*The White Guard* is set during the Ukrainian war of independence, a conflict seen by Ukrainian nationalists as a failed war of independence and by Russian/Soviet nationalists as a successful liberation of Ukraine from Western, especially German, control. It is a complex, multi-party conflict involving Ukrainian nationalists, White Russians, Germany, and the Bolsheviks. The family at the center of the novel live in Kiev, are of Russian heritage, and are Tsarist (i.e., they oppose the October Revolution). The novel is controversial in Ukraine, primarily in the eyes of Ukrainian nationalists, who obviously dislike the portrayal of the nationalist army. A movie version of the book was even banned in the 2010s for "denigrating" Ukrainian culture.

This is a really great war novel. The most impressive element is the thick atmosphere, the sense of confusion, fear, and dread that pervades everything the characters are doing. The war is happening but for the residents of Kiev it is happening off screen, outside their houses and apartments. Gunshots and explosions are heard in the distance; the characters try to wring sense from their direction, timing, frequency. They hear rumors about the nationalists, the Germans, the Bolsheviks, but ultimately they cannot tell what is happening, who is winning, or what that means for them. There is a sense that some great blood-letting is coming. We get multiple references to Revelations, rivers and fountains of water turning to blood. Very metal.

It seems to me that Bulgakov is capturing a deep truth about how war is experienced by civilians, particularly in urban areas. Life in some sense continues but there is this constant search for information, to interpret what is going on and what is likely to happen so that preparations can be made. And civilians view the warring actors primarily through the prism of risk and safety. Even the Turbins, who have ideological affinities in the fight, seem to view all of the warring actors with equal foreboding.

The novel also has a great sense of place. You really feel like you are in this city, in the winter, during a war. There are so many incredible scenes. One that stands out is near the end, at the morgue, where the main character has to sort through bodies and stench to identify a friend.

Something I kept coming back to was how "neutral" Bulgakov and the Turbins seem to feel towards the different warring parties. They certainly fear Petlyura's army and would prefer he did not take the city. At the same time, it seems clear they would simply live with that reality. The same, more or less, can be said of their view of the Bolsheviks, who are on the precipice of taking the city at the end of the novel. For most of the novel, whether Ukraine falls to the nationalists or the Bolsheviks seems equally bad to the Turbins. And yet the decision to start and end the novel with the lynching of a Jewish man by Ukrainian nationalists seems important. The quote at the end places blame for the bloodshed on the nationalists as well.

A fun anecdote about Bulgakov from Kotkin's *Stalin* series is that Stalin seemed to be a big fan (huge fan of the theater generally). Even though censors wanted to ban Bulgakov's work, about a White Russian family, he basically let it slide.
