---
title: "When the Clock Broke"
date: "2024-06-05"
author: "Juan Tellez"
categories:
  - books
  - history
  - usa
---

> With the inspiration of the death of the Soviet Union before us, we now know that it can be done. With Pat Buchanan as our leader, we shall break the clock of social democracy. We shall break the clock of the Great Society. We shall break the clock of the welfare state. We shall break the clock of the New Deal. We shall repeal the twentieth century.

I'm still not sure how we went from a world where newspapers with large teams, high-quality editing, expensive reporting, and numerous "big deal" op-ed writers would struggle to get people to sign up for $20 a month, to now, where an individual writer producing blog posts with often no editing, at unspecified intervals, can get many people to fork over $5 a month. I've tried subscribing to a few but I don't even like the rambling, long-form blog format for free, let alone paying for it.

Anyway, this is part of John Ganz's fame (though apparently he now also writes for The Nation). I had never read John Ganz before this book, but I am impressed. This could easily be my favorite book of the year. The writing is superb, and the level of detail he wrings out of the cast of characters — people you think you "know," like David Duke — reminds me of Rick Perlstein's work. But while Perlstein's books are way too long, Ganz cuts through the fat.

The book's thesis — never fully elaborated, even in the introduction, just left to the reader to connect the dots (very cool; the antithesis of academic writing which needs to spell everything out, down to an enumerated list of what each chapter is about, even though, ironically, academic writing is supposedly aimed at a more "specialized" audience) — is that the early 1990s is *the* period to look at to understand the current MAGA-right's roots. I left the book feeling like I understood something new about Trump, MAGA, and whatever is going on with the people in the Thiel-verse.

There are many parallels between the '90s and today. The chapter on David Duke alone is worth the price of admission. His racism is obviously well-known, but the fact that he was a major grifter (constantly trying to raise a buck off his supporters), vain (he got a ton of plastic surgery), and good at TV makes for an uncanny resemblance to Trump at times.

The paleoconservatives, also discussed here, are a clear intellectual influence on MAGA. The idea that America is in decline, that there's a new world order, that Americans are being taken advantage of by foreigners (at that time, it was Japan that drew ire), etc. — that's all in MAGA, but especially the hatred of the more neocon wing of the Republican Party. All of this is captured perfectly in Rothbard's essay advocating for a radical, populist conservatism.

Even culturally, you have the rise of a loneliness epidemic in the discourse, especially among young men; concern about the rise of talk radio and parasocial relationships (a clear analog to today's podcasts); a moral panic about crime in urban areas; and of course, the Rodney King trial giving way to riots, a clear analog to the summer of Floyd (one of many interesting details being that the beating was caught on camcorder by a neighbor, the footage effectively going viral before virality was a thing); and a Democratic Party that feels it has lost too many recent elections, with an ascendant moderate wing blaming losses to Reagan on the party's progressive faction.

Many similarities, but what is different? The big difference to me seems to be Bill Clinton. In response to a cultural turn to the right, Democrats put up a candidate who was willing to embody very conservatively coded policy positions *and* persona. For example, Clinton famously flew back to Arkansas to oversee the execution of a man on death row with significant mental deficiencies. He didn't just do this, he *campaigned* on it, which is wild to think about a Democrat doing today. As far as I can see, there is nothing like this emerging within the Democratic Party. But who knows; maybe this is the year.

PS: the chapter on Ruby Ridge and the white nationalist movement was also fascinating. Would read a book just on that.
