---
title: "Your Two-Year-Old: Terrible or Tender"
date: "2025-08-14"
author: "Juan Tellez"
categories:
  - books
  - parenting
---

This book is part of a series by the child developmental psychologist Louise Bates Ames. Each short book covers a year in the life of the child. The books cover, in broad strokes, how the child is changing psychologically, socially, emotionally, physically, etc.

I was motivated to read this because my two-year-old was driving me insane, nearly to the point of tears. I truly wanted to know: what the fuck is going on in there? Why is he doing all this?

I have to say: I got a lot out of reading this. Short, to the point, and the right tone for me as a parent: fairly relaxed, low stakes, more about adjusting your expectations to your child than what more contemporary child-rearing books tend to emphasize, which is *improving* or *maximizing* your child in some respect. I feel that I understand my two-year-old better after reading.

If I had to characterize Ames's approach for a child this age, it is to avoid confrontation, which does not mean caving to the child's demands — more in the way that in judo you use your opponent's momentum against them. Basically, where you can avoid confrontation, avoid it: don't ask questions where the answer can be "no" or where they can refuse without consequence, because they will. At two, the child is testing the boundaries around what is possible, discovering to some degree their autonomy. They will refuse, reject, want to do the opposite of what you request almost by nature.

One parental instinct here is to say "that is unacceptable," the world does not revolve around them, I will hold my ground. Ames would say this is basically fruitless because the refusal is literally part of the developmental stage they are in. And it is a stage; they will not stay there. It is therefore OK and advisable to instead leverage the fact that you are much smarter than them to divert their attention, change the subject, etc. At least this week, I feel like this works; who knows about the next.

The book has a fair number of bad reviews, due I think to its age (written in the 1970s), which shows in many parts. Things like the book warning you not to let your kid touch the dash when they're riding in the front seat with you is funny now. There's also a ton of gendered assumptions in here with respect to mothers and fathers. Doesn't bother me; seems easy enough to mentally replace "a stern warning from Dad" with "a stern warning from the more strict parent of the two / the most intimidating member of the polycule." I actually found it touching how much of the book felt timeless.

One last reaction is that as someone in the social sciences, I can't help but be skeptical about the harder claims in the book. How, exactly, could Ames "know" what is going on in the child's mind? She also breaks stages down to six-month intervals, which seems impossibly precise. I personally do not remember what my son was like at two years versus two-and-a-half versus now. Of course, Ames is careful to note that all children are different, and so basically all of what she says could not apply in your particular instance. So... what are we doing here? I guess you just have to believe.

Worth the read. I bought year three too. Do I peek ahead to see what this monster has in store for me or leave it as a surprise?
