---
title: "Zen at War"
date: "2025-11-21"
author: "Juan Tellez"
categories:
  - books
  - history
  - war
  - philosophy
  - religion
  - japan
---

If there's one religion that, at least at the level of stereotype, seems least amenable to violence, it is Buddhism. Yet Buddhists have and continue to commit violence in different parts of the world. How do Buddhists make sense of their actions in light of their beliefs? Are they hypocrites, "fake" Buddhists, or is there some doctrinal basis for violence in the belief system? *Zen at War* examines this question around the time of Japan's rising imperial ambitions, from its wars with China and Russia, conquest of Korea, and then through WW2. This book is interesting on two fronts.

First, rather than focus on soldiers or military leaders who might nominally be Buddhists but are primarily something else, Brian Daizen Victoria focuses on the harder case of clergy, Zen masters, and prominent Buddhist leaders — the most serious of practitioners. Here, the result is very depressing: the Buddhist leadership, top to bottom, justified and supported Japan's war effort and imperial ambitions. One could imagine a religion that supported war via charity, taking care of the sick, supporting the war effort in an indirect way. But Japanese Buddhists aggressively propagandized in favor of the war effort and its inherent justice. In Victoria's telling, this was ultimately about securing Buddhism's place within the Japanese state, a status that was shaky especially early on, when periods of nationalist fervor saw the state advocate for indigenous Shinto religions over the foreign-born Buddhist religion. A few Buddhists, especially those closer to laymen than priests, did resist, but paid dearly. Interestingly, many of these were socialist or socialist-adjacent.

Did these leaders do this cynically? And did their actions have some basis in Buddhist teachings? Victoria goes into painstaking detail about how Buddhist leadership justified Japanese imperialism through Buddhist doctrine. Personally, I did not find any of this convincing; it all sounded like the kind of vague, religious mumbo-jumbo logic we've heard elsewhere. To me, it seems so nakedly cynical one wonders if these people ever believed the doctrine in the first place.

The second part of what makes this book interesting is that Brian Daizen Victoria is himself a Zen Buddhist priest. His interest in this topic came from his anti-war activism during the Vietnam War, which put him at odds with American Buddhist leadership. The Zen Buddhists do not come across well in this book, which begs the question of how Victoria can sit with his beliefs and doctrinal affiliation while being so aware of the tradition's history. I personally could not stomach it.

This book is well done but I'm giving it a low rating because of how narrow it is. There's not a lot here that is generalized; it's a deep history of a specific set of actors in Japanese Buddhism.
